name: 'Conventional Commits Linter'

description: 'Lint commits'

runs:
  using: "composite"
  steps:
    - run: |
        test "" != $(git log --invert-grep --extended-regexp --grep="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([[:alnum:]._-]+\))?(!)?: ([[:alnum:]])+([[:space:][:print:]]*)") || {
          exit 1
        }
      shell: sh